name: 'Config entity example'
type: module
description: 'An example module showing how to create a config entity type.'
package: Example modules
# core: 8.x
dependencies:
  - examples

# Information added by Drupal.org packaging script on 2016-06-15
version: '8.x-1.x-dev'
core: '8.x'
project: 'examples'
datestamp: 1466011326
